#!/bin/bash
# This isn't a bash script, but that #! should give
# us pretty highlighting in most editors.


# Files and extensions we usually want to ignore.
# if you're making a new bundle, it's a good idea to
# copy this part.
.*/00readme\.txt
.*/LICENSE\.md
.*/Makefile
.*/README
.*/README.md
.*/readme\.txt
.*/ls-R
.*\.fmt
.*\.log
.*\.lua
.*\.mf
.*\.pl
.*\.ps
# End "always ignore" section.


# Bundle-specific ignore patterns



# I don't think tectonic has xindy support.
# Ignore for now, causes many conflicts
/texlive/xindy/.*

# We may need this, but exclude for now.
# Also causes many conflicts.
/texlive/tex4ht/.*

# These require pLaTeX2e, tectonic uses XeTeX
/texlive/tex/uplatex/.*
/texlive/tex/uptex/.*


# Other odd tex formats & unnecessary files
/texlive/tex/cslatex/.*
/texlive/tex/csplain/.*
/texlive/tex/ptex/.*
/texlive/tex/platex/.*
/texlive/tex/lollipop/.*
/texlive/tex/context/.*
/texlive/context/.*
/texlive/texdoc/.*
/texlive/texdoctk/.*
/texlive/texconfig/.*
/texlive/scripts/.*
/texlive/dvips/.*
/texlive/asymptote/.*
/texlive/makeindex/.*
/texlive/luatex-cache/.*
/texlive/hb2gf/.*
/texlive/chktex/.*
/texlive/source/.*
/texlive/doc/.*
/texlive/tex/luatex/.*
/texlive/tex/lualatex/.*


# Discontinued project
# (Why is this even in texlive?)
/texlive/tex/lambda/.*
/texlive/omega/.*