#!/bin/bash
# This isn't a bash script, but that #! should give
# us pretty highlighting in most editors.


# Files and extensions we usually want to ignore.
# if you're making a new bundle, it's a good idea to
# copy this part.
.*/00readme\.txt
.*/LICENSE\.md
.*/Makefile
.*/README
.*/README.md
.*/readme\.txt
.*/ls-R
.*\.fmt
.*\.log
.*\.lua
.*\.mf
.*\.pl
.*\.ps
# End "always ignore" section.


# Bundle-specific ignore patterns




# Ignore latex-dev files that are also in latesx.
# we do this individually because ignoring the whole dir breaks latex.ltx
# I'm not sure why that happens, needs further investigation.
# 
# BAD:
#/tex/latex-dev/.*


# Dots below aren't escaped, but there's nothing else those patterns match anyway.

# These differ by content
/tex/latex-dev/base/ltnews.cls
/tex/latex-dev/latex-lab/latex-lab-footnotes.ltx
/tex/latex-dev/base/latexrelease.sty
/tex/latex-dev/base/latex.ltx
/tex/latex-dev/latex-lab/latex-lab-footmisc.ltx
/tex/latex-dev/base/doc.sty
/tex/latex-dev/firstaid/latex2e-first-aid-for-external-files.ltx
/tex/latex-dev/latex-lab/new-or-latex-lab-testphase.ltx
/tex/latex-dev/latex-lab/tagpdf-latex-lab-testphase.ltx
/tex/latex-dev/latex-lab/phase-I-latex-lab-testphase.ltx
/tex/latex-dev/latex-lab/phase-II-latex-lab-testphase.ltx

# These differ from files in /tex/latex only by date.
/tex/latex-dev/base/textcomp-2018-08-11.sty
/tex/latex-dev/base/ot1cmfr.fd
/tex/latex-dev/base/ot1cmr.fd
/tex/latex-dev/base/ot1enc.def
/tex/latex-dev/base/ot1lcmss.fd
/tex/latex-dev/base/ot2enc.dfu
/tex/latex-dev/base/ot4enc.def
/tex/latex-dev/base/omslcmsy.fd
/tex/latex-dev/base/preload.cfg
/tex/latex-dev/base/proc.cls
/tex/latex-dev/base/report.sty
/tex/latex-dev/base/size12.clo
/tex/latex-dev/base/slides.def
/tex/latex-dev/base/structuredlog.sty
/tex/latex-dev/base/t1cmdh.fd
/tex/latex-dev/base/t1cmfr.fd
/tex/latex-dev/base/omsenc.def
/tex/latex-dev/base/omlcmm.fd
/tex/latex-dev/base/next.def
/tex/latex-dev/base/omlenc.def
/tex/latex-dev/base/omllcmm.fd
/tex/latex-dev/base/omscmr.fd
/tex/latex-dev/base/t1cmss.fd
/tex/latex-dev/base/t1cmtt.fd
/tex/latex-dev/base/t1cmvtt.fd
/tex/latex-dev/base/t1lcmtt.fd
/tex/latex-dev/base/textcomp.sty
/tex/latex-dev/base/tracefnt.sty
/tex/latex-dev/base/ts1cmr.fd
/tex/latex-dev/base/ts1enc.dfu
/tex/latex-dev/base/tuenc.def
/tex/latex-dev/base/tulmdh.fd
/tex/latex-dev/base/tulmr.fd
/tex/latex-dev/base/tulmvtt.fd
/tex/latex-dev/base/ucmr.fd
/tex/latex-dev/base/ucmss.fd
/tex/latex-dev/base/ucmtt.fd
/tex/latex-dev/base/ulasy.fd
/tex/latex-dev/base/ullasy.fd
/tex/latex-dev/base/utf8-2018
/tex/latex-dev/base/utf8.def
/tex/latex-dev/base/utf8enc.dfu
/tex/latex-dev/base/newlfont.sty
/tex/latex-dev/base/nfssfont.tex
/tex/latex-dev/base/oldlfont.sty
/tex/latex-dev/base/omlcmr.fd
/tex/latex-dev/base/omscmsy.fd
/tex/latex-dev/base/omsenc.dfu
/tex/latex-dev/base/omxcmex.fd
/tex/latex-dev/base/omxlcmex.fd
/tex/latex-dev/base/openbib.sty
/tex/latex-dev/base/ot1cmdh.fd
/tex/latex-dev/base/ot1cmfib.fd
/tex/latex-dev/base/ot1enc.dfu
/tex/latex-dev/base/ot1cmss.fd
/tex/latex-dev/base/ot1cmtt.fd
/tex/latex-dev/base/ot1cmvtt.fd
/tex/latex-dev/base/ot1lcmtt.fd
/tex/latex-dev/base/t1cmr.fd
/tex/latex-dev/base/t1cmfib.fd
/tex/latex-dev/base/syntonly.sty
/tex/latex-dev/base/slides.sty
/tex/latex-dev/base/showidx.sty
/tex/latex-dev/base/size10.clo
/tex/latex-dev/base/size11.clo
/tex/latex-dev/base/t1enc.def
/tex/latex-dev/base/t1enc.dfu
/tex/latex-dev/base/t1enc.sty
/tex/latex-dev/base/t1lcmss.fd
/tex/latex-dev/base/t2aenc.dfu
/tex/latex-dev/base/t2benc.dfu
/tex/latex-dev/base/t2cenc.dfu
/tex/latex-dev/base/testpage.tex
/tex/latex-dev/base/slides.cls
/tex/latex-dev/base/sfonts.def
/tex/latex-dev/base/report.cls
/tex/latex-dev/base/proc.sty
/tex/latex-dev/base/preload.ltx
/tex/latex-dev/base/x2enc.dfu
/tex/latex-dev/base/ts1cmss.fd
/tex/latex-dev/base/ts1cmtt.fd
/tex/latex-dev/base/ts1cmvtt.fd
/tex/latex-dev/base/ts1enc.def
/tex/latex-dev/base/tulmss.fd
/tex/latex-dev/base/tulmssq.fd
/tex/latex-dev/base/tulmtt.fd
/tex/latex-dev/base/doc.sty4
/tex/latex/latex-lab/documentmetadata-support.ltx
/tex/latex/base/atbegshi-ltx.sty
/tex/latex-dev/base/shortvrb.sty
/tex/latex-dev/base/applemac.def
/tex/latex-dev/base/article.cls
/tex/latex-dev/base/article.sty
/tex/latex-dev/base/bezier.sty
/tex/latex-dev/base/bk10.clo
/tex/latex-dev/base/cp1250.def
/tex/latex-dev/base/cp1252.def
/tex/latex-dev/base/cp1257.def
/tex/latex-dev/base/cp437de.def
/tex/latex-dev/base/decmulti.def
/tex/latex-dev/base/docstrip.tex
/tex/latex-dev/base/exscale.sty
/tex/latex-dev/base/fleqn.clo
/tex/latex-dev/base/fleqn.sty
/tex/latex-dev/base/fltrace.sty
/tex/latex-dev/base/fontenc.sty
/tex/latex-dev/base/fontmath.cfg
/tex/latex-dev/base/fontmath.ltx
/tex/latex-dev/base/fonttext.ltx
/tex/latex-dev/base/graphpap.sty
/tex/latex-dev/base/hyphen.ltx
/tex/latex-dev/base/ifthen.sty
/tex/latex-dev/base/inputenc.sty
/tex/latex-dev/base/lablst.tex
/tex/latex-dev/base/latin10.def
/tex/latex-dev/base/latin3.def
/tex/latex-dev/base/latin4.def
/tex/latex-dev/base/latin5.def
/tex/latex-dev/base/leqno.clo
/tex/latex-dev/base/ltxcheck.tex
/tex/latex-dev/base/ltxdoc.cfg
/tex/latex-dev/base/ltxdoc.cls
/tex/latex-dev/base/ly1enc.dfu
/tex/latex-dev/base/utf8-2018.def
/tex/latex-dev/base/alltt.sty
/tex/latex-dev/base/ansinew.def
/tex/latex-dev/base/ascii.def
/tex/latex-dev/base/bk11.clo
/tex/latex-dev/base/bk12.clo
/tex/latex-dev/base/book.cls
/tex/latex-dev/base/book.sty
/tex/latex-dev/base/cp437.def
/tex/latex-dev/base/cp850.def
/tex/latex-dev/base/cp852.def
/tex/latex-dev/base/cp858.def
/tex/latex-dev/base/cp865.def
/tex/latex-dev/base/fixltx2e.sty
/tex/latex-dev/base/flafter.sty
/tex/latex-dev/base/idx.tex
/tex/latex-dev/base/latex209.def
/tex/latex-dev/base/latexsym.sty
/tex/latex-dev/base/latin1.def
/tex/latex-dev/base/latin2.def
/tex/latex-dev/base/latin9.def
/tex/latex-dev/base/lcyenc.dfu
/tex/latex-dev/base/leqno.sty
/tex/latex-dev/base/letter.cls
/tex/latex-dev/base/letter.sty
/tex/latex-dev/base/ltluatex.tex
/tex/latex-dev/base/macce.def
/tex/latex-dev/base/makeidx.sty
/tex/latex-dev/base/fix-cm.sty
/tex/latex-dev/base/atveryend-ltx.sty
/tex/latex-dev/base/fonttext.cfg



# A few CSLaTeX files conflict with babel, ignore them for now.
/tex/cslatex/.*
/tex/csplain/.*


# I don't think tectonic has xindy support.
# Ignore for now, causes many conflicts
/xindy/.*

# We may need this, but exclude for now.
# Also causes many conflicts.
/tex4ht/.*

# These require pLaTeX2e, tectonic uses XeTeX
/tex/uplatex/.*
/tex/uptex/.*

# These require LuaLaTeX, tectonic uses XeTeX
/tex/luatex/.*
/tex/lualatex/.*

# Other odd tex formats & unnecessary files
/tex/ptex/.*
/tex/platex/.*
/tex/lollipop/.*
/tex/context/.*
/context/.*
/texdoc/.*
/texdoctk/.*
/texconfig/.*
/scripts/.*
/dvips/.*
/asymptote/.*
/makeindex/.*
/luatex-cache/.*
/hb2gf/.*
/chktex/.*
/source/.*
/doc/.*


# Discontinued project
# (Why is this even in texlive?)
/tex/lambda/.*
/omega/.*


# Currently broken, fix later
/tex/latex/fithesis/.*


# Identical conflicts
# We need to handle this better later.
/tex/latex-dev/tools/.tex
/tex/latex-dev/tools/afterpage.sty
/tex/latex-dev/amsmath/amsbsy.sty
/tex/latex-dev/amsmath/amscd.sty
/tex/latex-dev/amsmath/amsgen.sty
/tex/latex-dev/amsmath/amsmath-2018-12-01.sty
/tex/latex-dev/amsmath/amsmath.sty
/tex/latex-dev/amsmath/amsopn.sty
/tex/latex-dev/amsmath/amstex.sty
/tex/latex-dev/amsmath/amstext.sty
/tex/latex-dev/amsmath/amsxtra.sty
/fonts/misc/xetex/fontmapping/polyglossia/arabicdigits.map
/fonts/misc/xetex/fontmapping/polyglossia/arabicdigits.tec
/tex/latex-dev/tools/array-2016-10-06.sty
/tex/latex-dev/tools/array-2020-02-10.sty
/tex/latex-dev/tools/array.sty
/tex/latex-dev/tools/bm.sty
/tex/latex-dev/tools/calc.sty
/tex/latex-dev/graphics/color.sty
/tex/latex-dev/tools/dcolumn.sty
/tex/latex-dev/tools/delarray.sty
/tex/latex-dev/base/doc-2016-02-15.sty
/tex/latex-dev/base/doc-2021-06-01.sty
/tex/latex-dev/graphics/dvipdf.def
/tex/latex-dev/graphics/dvipsnam.def
/tex/latex-dev/graphics/dvipsone.def
/tex/latex-dev/tools/e.tex
/tex/latex-dev/graphics/dviwin.def
/tex/latex-dev/graphics/emtex.def
/tex/latex-dev/tools/enumerate.sty
/tex/latex-dev/graphics/epsfig.sty
/tex/latex-dev/firstaid/everysel-ltx.sty
/fonts/misc/xetex/fontmapping/polyglossia/farsidigits.map
/fonts/misc/xetex/fontmapping/polyglossia/farsidigits.tec
/tex/latex-dev/firstaid/filehook-ltx.sty
/tex/latex-dev/tools/fontsmpl.sty
/tex/latex-dev/tools/fontsmpl.tex
/fonts/afm/public/fouriernc/fourier-mcl.afm
/fonts/afm/public/fouriernc/fourier-ml.afm
/fonts/afm/public/fouriernc/fourier-mlb.afm
/fonts/afm/public/fouriernc/fourier-mlit.afm
/fonts/afm/public/fouriernc/fourier-mlitb.afm
/fonts/afm/public/fouriernc/fourier-ms.afm
/tex/latex-dev/tools/ftnright.sty
/tex/latex-dev/graphics/graphics-2017-06-25.sty
/tex/latex-dev/graphics/graphics.sty
/tex/latex-dev/graphics/graphicx.sty
/tex/latex-dev/tools/h.tex
/tex/latex-dev/tools/hhline.sty
/tex/generic/ibygrk/ibycus4.map
/tex/latex-dev/graphics/keyval.sty
/tex/latex-dev/tools/indentfirst.sty
/tex/latex-dev/tools/layout.sty
/tex/latex-dev/tools/longtable-2020-01-07.sty
/tex/latex-dev/tools/longtable.sty
/tex/latex-dev/base/lppl.tex
/tex/latex-dev/graphics/lscape.sty
/tex/latex-dev/graphics/mathcolor.ltx
/tex/latex-dev/base/ltxguide.cls
/tex/latex-dev/base/minimal.cls
/tex/latex-dev/tools/multicol-2017-04-11.sty
/tex/latex-dev/tools/multicol-2019-10-01.sty
/tex/latex-dev/tools/multicol.sty
/tex/latex-dev/graphics/pctex32.def
/tex/latex-dev/graphics/pctexhp.def
/tex/latex-dev/graphics/pctexps.def
/tex/latex-dev/graphics/pctexwin.def
/fonts/tfm/public/mathdesign/mdput/putb8a.tfm
/fonts/tfm/public/mathdesign/mdput/putb8x.tfm
/fonts/tfm/public/mathdesign/mdput/putbi8a.tfm
/fonts/tfm/public/mathdesign/mdput/putr8a.tfm
/fonts/tfm/public/mathdesign/mdput/putr8x.tfm
/fonts/tfm/public/mathdesign/mdput/putri8a.tfm
/fonts/afm/public/pxfonts/pxbsyb.afm
/tex/latex-dev/tools/q.tex
/tex/latex-dev/tools/r.tex
/tex/latex-dev/tools/rawfonts.sty
/tex/latex-dev/graphics/rotating.sty
/tex/latex-dev/tools/s.tex
/tex/latex-dev/base/sample2e.tex
/tex/latex-dev/tools/shellesc.sty
/tex/latex-dev/tools/showkeys-2014-10-28.sty
/tex/latex-dev/tools/showkeys.sty
/tex/latex-dev/base/small2e.tex
/tex/latex-dev/tools/somedefs.sty
/tex/latex-dev/base/source2edoc.cls
/tex/xelatex/tabriz-thesis/tabriz-thesis.cls
/tex/latex-dev/tools/tabularx.sty
/tex/latex-dev/graphics/tcidvi.def
/tex/latex-dev/base/texsys.cfg
/tex/latex-dev/tools/thb.sty
/tex/latex-dev/tools/thc.sty
/tex/latex-dev/tools/thcb.sty
/tex/latex-dev/tools/theorem.sty
/tex/latex-dev/tools/thm.sty
/tex/latex-dev/tools/thmb.sty
/tex/latex-dev/tools/thp.sty
/tex/latex-dev/tools/trace.sty
/tex/latex-dev/graphics/trig.sty
/tex/latex-dev/graphics/truetex.def
/tex/latex-dev/tools/varioref-2016-02-16.sty
/tex/latex-dev/tools/varioref.sty
/tex/latex-dev/tools/verbatim.sty
/tex/latex-dev/tools/verbtest.tex
/tex/latex-dev/tools/x.tex
/tex/latex-dev/tools/xr.sty
/tex/latex-dev/tools/xspace.sty

# Probably don't need?
# (there's a xelatex alternative)
/tex/xetex/xetex-pstricks/pstricks.con
/tex/generic/pstricks/pstricks.con


# Misc conflicts.
# We'll need to implement proper paths to fix these.
/fonts/enc/dvips/archivo/.*
/fonts/enc/dvips/alfaslabone/.*
/fonts/enc/dvips/opensans/.*
/fonts/enc/dvips/andika/.*
/fonts/enc/dvips/nunito/.*
/tex/latex/ledmac/afoot.sty
/fonts/cmap/adobemapping/cmap-resources/Adobe-CNS1-7/cid2code.txt
/fonts/cmap/adobemapping/cmap-resources/Adobe-GB1-5/cid2code.txt
/fonts/cmap/adobemapping/cmap-resources/Adobe-Korea1-2/cid2code.txt
/fonts/cmap/adobemapping/cmap-resources/Adobe-Japan1-7/cid2code.txt
/fonts/cmap/adobemapping/cmap-resources/Adobe-KR-9/cid2code.txt
/fonts/type1/public/mathdesign/mdput/md-utrma.pfb
/fonts/map/dvipdfm/lm/lm-rm.map
/fonts/map/dvipdfm/lm/lm-math.map
/fonts/map/dvipdfm/lm/lm-ec.map
/fonts/map/dvipdfm/lm/lm-texnansi.map

/tex/latex/tikz-dependency/pgfmanual.prettyprinter.code.tex
/tex/latex/pgf/doc/pgfmanual.pdflinks.code.tex
/tex/latex/tikz-dependency/pgfmanual.code.tex
/tex/latex/cmap/t1.cmap
/tex/latex/cmap/ot1.cmap
