#!/bin/bash
# This isn't a bash script, but that #! should give
# us pretty highlighting in most editors.


# Files and extensions we usually want to ignore.
# if you're making a new bundle, it's a good idea to
# copy this part.
.*/00readme\.txt
.*/LICENSE\.md
.*/Makefile
.*/README
.*/README.md
.*/ls-R
.*\.fmt
.*\.log
.*\.lua
.*\.mf
.*\.pl
.*\.ps
# End "always ignore" section.


# Bundle-specific ignore patterns
/tex/latex-dev/.*